SELECT
    QUERY_ID,
    QUERY_TEXT,
    USER_NAME,
    START_TIME
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(day, -30, CURRENT_TIMESTAMP())
  AND (
      QUERY_TEXT ILIKE '%CORTEX%'
      OR QUERY_TEXT ILIKE '%AI_EMBED%'
      OR QUERY_TEXT ILIKE '%VECTOR_COSINE_SIMILARITY%'
  )
ORDER BY START_TIME DESC;
